version: '3.8'

services:
  db-vehiculos:
    image: mysql:8.0
    container_name: sicae-db-vehiculos
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_DATABASE: sicaevehiculo
    ports:
      - "3308:3306"
    volumes:
      - mysqlvdata:/var/lib/mysql
      - ./scripts/sicaevehiculo.sql:/docker-entrypoint-initdb.d/sicaevehiculo.sql
    networks:
      - sicae-network

  sicae-vehiculos:
    build:
      context: ./sicae-vehiculos
      dockerfile: Dockerfile
    container_name: sicae-vehiculos-app
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-vehiculos:3306/sicaevehiculo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql_password
    depends_on:
      - db-vehiculos
    networks:
      - sicae-network

volumes:
  mysqlvdata:

networks:
  sicae-network:
    external: true