spring.application.name=sicae-vehiculos
server.port=8083

spring.datasource.url=jdbc:mysql://db-vehiculos:3306/sicaevehiculo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=parking_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=uv.listi.sicae.vehiculos.model